/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Progreso;
import java.sql.*;
/**
 *
 * @author Sergio
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        setTitle("Administrador");
        setLocationRelativeTo(null);
        setSize(468, 479);//tamaño de la interfaz
        setResizable(false);//evita que el usuruario modifica las dimenciones de la interfaz
        setTitle("Acceso al sistema");//nombre de la interfaz
        setLocationRelativeTo(null);//Sentrar la interfaz
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        btn_Medico = new javax.swing.JButton();
        btn_Enfermero = new javax.swing.JButton();
        btn_Ingeniero = new javax.swing.JButton();
        btn_Paciente = new javax.swing.JButton();
        btn_Equipo = new javax.swing.JButton();
        btn_User = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Administrador");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        btn_Medico.setBackground(new java.awt.Color(102, 0, 102));
        btn_Medico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_Medico.setForeground(new java.awt.Color(255, 255, 255));
        btn_Medico.setText("Registrar Medico");
        btn_Medico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MedicoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, -1));

        btn_Enfermero.setBackground(new java.awt.Color(102, 0, 102));
        btn_Enfermero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_Enfermero.setForeground(new java.awt.Color(255, 255, 255));
        btn_Enfermero.setText("Registrar Enfermero");
        btn_Enfermero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Enfermero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EnfermeroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Enfermero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, -1));

        btn_Ingeniero.setBackground(new java.awt.Color(102, 0, 102));
        btn_Ingeniero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_Ingeniero.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ingeniero.setText("Registrar Ingeniero");
        btn_Ingeniero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Ingeniero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngenieroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Ingeniero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, -1));

        btn_Paciente.setBackground(new java.awt.Color(102, 0, 102));
        btn_Paciente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_Paciente.setForeground(new java.awt.Color(255, 255, 255));
        btn_Paciente.setText("Registro Paciente");
        btn_Paciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 140, -1));

        btn_Equipo.setBackground(new java.awt.Color(102, 0, 102));
        btn_Equipo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_Equipo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Equipo.setText("Registro Equipo");
        btn_Equipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EquipoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 140, -1));

        btn_User.setBackground(new java.awt.Color(102, 0, 102));
        btn_User.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_User.setForeground(new java.awt.Color(255, 255, 255));
        btn_User.setText("Gestor de Usuario");
        btn_User.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 140, -1));

        jButton7.setBackground(new java.awt.Color(102, 0, 102));
        jButton7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Salir");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.0.jpg"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MedicoActionPerformed
        // TODO add your handling code here:
        RegistroM res= new RegistroM();
        res.setVisible(true);
    }//GEN-LAST:event_btn_MedicoActionPerformed

    private void btn_EnfermeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EnfermeroActionPerformed
        // TODO add your handling code here:
        RegistroE res2= new RegistroE();
        res2.setVisible(true);
    }//GEN-LAST:event_btn_EnfermeroActionPerformed

    private void btn_IngenieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngenieroActionPerformed
        // TODO add your handling code here:
        RegistroI res3= new RegistroI();
        res3.setVisible(true);
    }//GEN-LAST:event_btn_IngenieroActionPerformed

    private void btn_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PacienteActionPerformed
        // TODO add your handling code here:
        RegistroP res4= new RegistroP();
        res4.setVisible(true);
    }//GEN-LAST:event_btn_PacienteActionPerformed

    private void btn_EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EquipoActionPerformed
        // TODO add your handling code here:
        RegistroEq res5= new RegistroEq();
        res5.setVisible(true);
    }//GEN-LAST:event_btn_EquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Enfermero;
    private javax.swing.JButton btn_Equipo;
    private javax.swing.JButton btn_Ingeniero;
    private javax.swing.JButton btn_Medico;
    private javax.swing.JButton btn_Paciente;
    private javax.swing.JButton btn_User;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
