/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Progreso;

import java.sql.*;
import javax.swing.JOptionPane;
import clases.Conexion;

/**
 *
 * @author Sergio
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new from
     */
    public Login() {
        initComponents();
        setSize(400, 550);//tamaño de la interfaz
        setResizable(false);//evita que el usuruario modifica las dimenciones de la interfaz
        setTitle("Acceso al sistema");//nombre de la interfaz
        setLocationRelativeTo(null);//Sentrar la interfaz

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Logo = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        txt_Contraseña = new javax.swing.JPasswordField();
        btn_Acceder = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Progreso/logo1.2.PNG"))); // NOI18N
        jLabel_Logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 70));

        txt_Usuario.setBackground(new java.awt.Color(102, 0, 102));
        txt_Usuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 330, 210, -1));

        txt_Contraseña.setBackground(new java.awt.Color(102, 0, 102));
        txt_Contraseña.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        txt_Contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Contraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 370, 210, -1));

        btn_Acceder.setBackground(new java.awt.Color(102, 0, 102));
        btn_Acceder.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn_Acceder.setForeground(new java.awt.Color(255, 255, 255));
        btn_Acceder.setText("Acceder");
        btn_Acceder.setBorder(null);
        btn_Acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccederActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 420, 210, 35));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Progreso/fondo3.0.jpg"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccederActionPerformed
        // TODO add your handling code here:
        String user = txt_Usuario.getText().trim();
        String pass = txt_Contraseña.getText().trim();

        if (user.equals("admin") && pass.equals("admin")) {

            new Administrador().setVisible(true);
            dispose();
        }

//        if(!user.equals("") || !pass.equals("")){
//        
//            try  {
//                Connection cn = Conexion.conectar();
//               PreparedStatement pst = cn.prepareStatement("select * from usuarios where username = '" + user 
//               + "' and Contraseña = '" + pass + "'");
//               
//                ResultSet rs = pst.executeQuery();
//                if(rs.next()){
//                    String tipo_nivel = rs.getString("tipo_nivel");
//                    String estatus = rs.getString("");
//                    
//                    if(tipo_nivel.equalsIgnoreCase("Administrador") && estatus.equalsIgnoreCase("Activo")){
//                        dispose();
//                        new Administrador().setVisible(true);
//                    }else if(tipo_nivel.equalsIgnoreCase("Medico") && estatus.equalsIgnoreCase("Activo")){
//                        dispose();
//                        new Medico().setVisible(true);
//                    }else if(tipo_nivel.equalsIgnoreCase("Ingeniero") && estatus.equalsIgnoreCase("Activo")){
//                        dispose();
//                        new Ingeniero().setVisible(true);
//                    }
//                }else{
//                    JOptionPane.showMessageDialog(null, "Datos de acceso incorrectos");
//                    txt_Usuario.setText("");
//                    txt_Contraseña.setText("estatus");
//                    
//
//                }
//            } catch (SQLException e){
//                System.err.println("Error en el boton Aceder" + e);
//                JOptionPane.showMessageDialog(null, "¡¡Error al iniciar secion!!, contacte al administrador.");
//            }
//        }  else {
//            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
//        }
    }//GEN-LAST:event_btn_AccederActionPerformed

    private void txt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsuarioActionPerformed


    }//GEN-LAST:event_txt_UsuarioActionPerformed

    private void txt_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Acceder;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JPasswordField txt_Contraseña;
    private javax.swing.JTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
