/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Progreso;
import java.sql.*;
/**
 *
 * @author Sergio
 */
public class RegistroM extends javax.swing.JFrame {

        
    /**
     * Creates new form RegistroM
     */
    public RegistroM() {
        initComponents();
        this.setLocationRelativeTo(null);//sentrar interfas grafica
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jbl_Nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jbl_Apellido = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jbl_Usuario = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        jbl_Contraseña = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JPasswordField();
        jbl_Especialidad = new javax.swing.JLabel();
        cmb_especialidad = new javax.swing.JComboBox<>();
        jbl_Sexo = new javax.swing.JLabel();
        rbt_hombre = new javax.swing.JRadioButton();
        rbt_Mujer = new javax.swing.JRadioButton();
        jbl_Fecha = new javax.swing.JLabel();
        dtc_fecha = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        label_status = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro Medico");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jbl_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jbl_Nombre.setText("Nombre:");
        getContentPane().add(jbl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(102, 0, 102));
        txt_nombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        jbl_Apellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_Apellido.setForeground(new java.awt.Color(255, 255, 255));
        jbl_Apellido.setText("Apellido");
        getContentPane().add(jbl_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txt_apellido.setBackground(new java.awt.Color(102, 0, 102));
        txt_apellido.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(255, 255, 255));
        txt_apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_apellido.setToolTipText("");
        txt_apellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        jbl_Usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        jbl_Usuario.setText("Nombre de usuario:");
        getContentPane().add(jbl_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txt_Usuario.setBackground(new java.awt.Color(102, 0, 102));
        txt_Usuario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

        jbl_Contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jbl_Contraseña.setText("Contraseña:");
        getContentPane().add(jbl_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txt_contraseña.setBackground(new java.awt.Color(102, 0, 102));
        txt_contraseña.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        txt_contraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 210, -1));

        jbl_Especialidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_Especialidad.setForeground(new java.awt.Color(255, 255, 255));
        jbl_Especialidad.setText("Especialidad:");
        getContentPane().add(jbl_Especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        cmb_especialidad.setBackground(new java.awt.Color(102, 0, 102));
        cmb_especialidad.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cmb_especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Pediatria ", "Cirugia", "Cardiologia", "Hematologia" }));
        cmb_especialidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmb_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

        jbl_Sexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_Sexo.setText("Sexo:");
        getContentPane().add(jbl_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        rbt_hombre.setBackground(new java.awt.Color(102, 0, 102));
        rbt_hombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        rbt_hombre.setForeground(new java.awt.Color(255, 255, 255));
        rbt_hombre.setText("Hombre");
        rbt_hombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(rbt_hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        rbt_Mujer.setBackground(new java.awt.Color(102, 0, 102));
        rbt_Mujer.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        rbt_Mujer.setForeground(new java.awt.Color(255, 255, 255));
        rbt_Mujer.setText("Mujer");
        rbt_Mujer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(rbt_Mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        jbl_Fecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_Fecha.setForeground(new java.awt.Color(255, 255, 255));
        jbl_Fecha.setText("Fecha de nacimiento ");
        getContentPane().add(jbl_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        dtc_fecha.setBackground(new java.awt.Color(102, 0, 102));
        dtc_fecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(dtc_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, -1));

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Progreso/add.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, 100));

        label_status.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(label_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jButton1.setText("Cargar imagen ");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 130, 120));

        jLabel_Wallpaper.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Wallpaper.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel_Wallpaper.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 620, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bd_medico", "root", "");
            PreparedStatement pst = cn.prepareStatement("INSERT INTO medicos"+"(Nombre,Apellido,Usuario,Contraseña,Especialidad, Sexo) VALUES"+"(?,?,?,?,?,?)");
            
            pst.setString(1, txt_nombre.getText().trim());
            pst.setString(2, txt_apellido.getText().trim());
            pst.setString(3, txt_Usuario.getText().trim());
            pst.setString(4, txt_contraseña.getText().trim());
            pst.setString(5, cmb_especialidad.getSelectedItem().toString());
            pst.setString(6, rbt_hombre.getText().trim());
            pst.setString(6, rbt_Mujer.getText().trim());
         // pst.setString(7, dtc_fecha.getText().trim());
            pst.executeUpdate();
            
            txt_nombre.setText("");
            txt_apellido.setText("");
            txt_Usuario.setText("");
            txt_contraseña.setText("");
            rbt_hombre.setText("");
            rbt_Mujer.setText("");
            
            label_status.setText("Registro exitoso.");
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_especialidad;
    private com.toedter.calendar.JDateChooser dtc_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jbl_Apellido;
    private javax.swing.JLabel jbl_Contraseña;
    private javax.swing.JLabel jbl_Especialidad;
    private javax.swing.JLabel jbl_Fecha;
    private javax.swing.JLabel jbl_Nombre;
    private javax.swing.JLabel jbl_Sexo;
    private javax.swing.JLabel jbl_Usuario;
    private javax.swing.JLabel label_status;
    private javax.swing.JRadioButton rbt_Mujer;
    private javax.swing.JRadioButton rbt_hombre;
    private javax.swing.JTextField txt_Usuario;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
